image: registry.gitlab.com/amadoruavs/amadoruavs.gitlab.io

variables:
  JEKYLL_ENV: production

stages:
  - deploy

pages:
  script:
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
